import type { DocsSidebarSection } from '../../toc';

export const ECOSYSTEM_SIDEBAR_SECTIONS: DocsSidebarSection[] = [
  {
    subheader: 'Ecosystem Docs',
    items: [
      {
        title: 'Home',
        path: '/ecosystem',
        icon: 'ic-dashboard',
        product: 'ecosystem',
      },
      {
        title: 'Huawei (Ascend)',
        path: '/ecosystem/huawei',
        icon: 'ic-file',
        product: 'ecosystem',
        children: [
          { title: 'Drivers & Runtime', path: '/ecosystem/huawei/driver-runtime' },
          {
            title: 'MindCluster',
            path: '/ecosystem/huawei/mindcluster',
            children: [
              { title: 'Packages', path: '/ecosystem/huawei/mindcluster/packages' },
              { title: 'Ascend Docker Runtime', path: '/ecosystem/huawei/mindcluster/ascend-docker-runtime' },
              { title: 'NPU Exporter', path: '/ecosystem/huawei/mindcluster/npu-exporter' },
              { title: 'Ascend Device Plugin', path: '/ecosystem/huawei/mindcluster/ascend-device-plugin' },
              { title: 'NodeD', path: '/ecosystem/huawei/mindcluster/noded' },
            ],
          },
        ],
      },
      {
        title: 'Hygon (DCU)',
        path: '/ecosystem/hygon',
        icon: 'ic-product',
        product: 'ecosystem',
        children: [
          { title: 'Driver Installation', path: '/ecosystem/hygon/driver-runtime' },
          {
            title: 'Kubernetes Components',
            path: '/ecosystem/hygon/k8s-components',
            children: [
              { title: 'Overview', path: '/ecosystem/hygon/k8s-overview' },
              { title: 'DCU-Label-Node', path: '/ecosystem/hygon/k8s-label-node' },
              { title: 'DCU-Exporter', path: '/ecosystem/hygon/k8s-exporter' },
              { title: 'DCU Device Plugin (Standard)', path: '/ecosystem/hygon/k8s-device-plugin-standard' },
              { title: 'DCU Device Plugin (MIG)', path: '/ecosystem/hygon/k8s-device-plugin-mig' },
              { title: 'vDCU Dynamic Splitting', path: '/ecosystem/hygon/k8s-vdcu-dynamic-splitting' },
              { title: 'FAQ', path: '/ecosystem/hygon/k8s-faq' },
            ],
          },
        ],
      },
      {
        title: 'NVIDIA (GPU)',
        path: '/ecosystem/nvidia',
        icon: 'ic-analytics',
        product: 'ecosystem',
        children: [
          { title: 'Drivers & Runtime', path: '/ecosystem/nvidia/driver-runtime' },
          {
            title: 'GPU Operator',
            path: '/ecosystem/nvidia/gpu-operator',
            children: [
              { title: 'Install & Verify', path: '/ecosystem/nvidia/gpu-operator/install' },
              { title: 'Node Labels (NFD / GFD)', path: '/ecosystem/nvidia/gpu-operator/node-labels' },
              { title: 'Device Plugin', path: '/ecosystem/nvidia/gpu-operator/device-plugin' },
              { title: 'DCGM Exporter', path: '/ecosystem/nvidia/gpu-operator/dcgm-exporter' },
              { title: 'MIG Partitioning', path: '/ecosystem/nvidia/gpu-operator/mig-manager' },
            ],
          },
          { title: 'Volcano & vGPU', path: '/ecosystem/nvidia/volcano-vgpu' },
          { title: 'FAQ', path: '/ecosystem/nvidia/faq' },
        ],
      },
      {
        title: 'Alibaba Cloud (PPU)',
        path: '/ecosystem/aliyun',
        icon: 'ic-banking',
        product: 'ecosystem',
        children: [
          { title: 'PPU Basics', path: '/ecosystem/aliyun/ppu-basics' },
          { title: 'Lingjun Node Pool', path: '/ecosystem/aliyun/lingjun-nodepool' },
          {
            title: 'Device Plugin',
            path: '/ecosystem/aliyun/device-plugin',
            children: [
              { title: 'Install & Verify', path: '/ecosystem/aliyun/device-plugin/install' },
              { title: 'Scheduling', path: '/ecosystem/aliyun/device-plugin/scheduling' },
              { title: 'MIG Partitioning', path: '/ecosystem/aliyun/device-plugin/mig' },
            ],
          },
          { title: 'Using PPU on the Platform', path: '/ecosystem/aliyun/platform-usage' },
          { title: 'FAQ', path: '/ecosystem/aliyun/faq' },
        ],
      },
      {
        title: 'AMD (Instinct / ROCm)',
        path: '/ecosystem/amd',
        icon: 'ic-subpaths',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/amd/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/amd/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/amd/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/amd/platform-support' },
          { title: 'FAQ', path: '/ecosystem/amd/faq' },
        ],
      },
      {
        title: 'Cambricon (MLU)',
        path: '/ecosystem/cambricon',
        icon: 'ic-params',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/cambricon/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/cambricon/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/cambricon/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/cambricon/platform-support' },
          { title: 'FAQ', path: '/ecosystem/cambricon/faq' },
        ],
      },
      {
        title: 'Moore Threads (MTT)',
        path: '/ecosystem/moore-threads',
        icon: 'ic-label',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/moore-threads/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/moore-threads/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/moore-threads/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/moore-threads/platform-support' },
          { title: 'FAQ', path: '/ecosystem/moore-threads/faq' },
        ],
      },
      {
        title: 'MetaX (Xiyun)',
        path: '/ecosystem/metax',
        icon: 'ic-order',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/metax/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/metax/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/metax/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/metax/platform-support' },
          { title: 'FAQ', path: '/ecosystem/metax/faq' },
        ],
      },
      {
        title: 'Biren Technology',
        path: '/ecosystem/biren',
        icon: 'ic-folder',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/biren/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/biren/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/biren/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/biren/platform-support' },
          { title: 'FAQ', path: '/ecosystem/biren/faq' },
        ],
      },
      {
        title: 'Iluvatar CoreX',
        path: '/ecosystem/iluvatar',
        icon: 'ic-invoice',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/iluvatar/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/iluvatar/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/iluvatar/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/iluvatar/platform-support' },
          { title: 'FAQ', path: '/ecosystem/iluvatar/faq' },
        ],
      },
      {
        title: 'Kunlunxin',
        path: '/ecosystem/kunlunxin',
        icon: 'ic-tour',
        product: 'ecosystem',
        children: [
          { title: 'Products & Software Stack', path: '/ecosystem/kunlunxin/products' },
          { title: 'Drivers & Container Runtime', path: '/ecosystem/kunlunxin/driver-runtime' },
          { title: 'Kubernetes Components', path: '/ecosystem/kunlunxin/k8s-components' },
          { title: 'Platform Support', path: '/ecosystem/kunlunxin/platform-support' },
          { title: 'FAQ', path: '/ecosystem/kunlunxin/faq' },
        ],
      },
      {
        title: 'HAMi',
        path: '/ecosystem/hami',
        icon: 'ic-kanban',
        product: 'ecosystem',
        children: [
          { title: 'Architecture & Scheduling', path: '/ecosystem/hami/architecture' },
          { title: 'Installation & Parameters', path: '/ecosystem/hami/install' },
          { title: 'Supported Devices & Resource Keys', path: '/ecosystem/hami/device-matrix' },
          { title: 'Platform Support', path: '/ecosystem/hami/platform-support' },
          { title: 'Requesting & Operating', path: '/ecosystem/hami/usage' },
          { title: 'FAQ', path: '/ecosystem/hami/faq' },
        ],
      },
      {
        title: 'Open Source Communities',
        path: '/ecosystem/open-source',
        icon: 'ic-course',
        product: 'ecosystem',
        children: [
          { title: 'Containers & Orchestration', path: '/ecosystem/open-source/container-orchestration' },
          { title: 'Frameworks & Inference', path: '/ecosystem/open-source/framework-inference' },
          { title: 'Observability & Operations', path: '/ecosystem/open-source/observability-ops' },
          { title: 'Artifacts & Security', path: '/ecosystem/open-source/artifacts-security' },
          { title: 'FAQ', path: '/ecosystem/open-source/faq' },
        ],
      },
    ],
  },
];
