import type { DocsSidebarSection } from '../../toc';

export const BOSS_SIDEBAR_SECTIONS: DocsSidebarSection[] = [
  {
    subheader: 'Boss Operations Platform',
    items: [
      {
        title: 'Home',
        path: '/docs/boss',
        icon: 'ic-params',
        product: 'boss',
      },
      {
        title: 'IAM',
        path: '/docs/boss/iam',
        icon: 'ic-lock',
        product: 'boss',
        children: [
          { title: 'User Management', path: '/docs/boss/iam/users' },
          { title: 'Tenant Management', path: '/docs/boss/iam/tenants' },
        ],
      },
      {
        title: 'Platform Operations',
        path: '/docs/boss/operations',
        icon: 'ic-analytics',
        product: 'boss',
        children: [
          { title: 'Cluster Management', path: '/docs/boss/operations/clusters' },
          { title: 'Tenants & Quotas', path: '/docs/boss/operations/tenants' },
          { title: 'Gateway Governance', path: '/docs/boss/operations/gateway' },
        ],
      },
      {
        title: 'System Templates',
        path: '/docs/boss/templates',
        icon: 'ic-file',
        product: 'boss',
      },
      {
        title: 'LLM Gateway',
        path: '/docs/boss/gateway',
        icon: 'ic-blog',
        product: 'boss',
        children: [
          { title: 'Channels', path: '/docs/boss/gateway/channels' },
          { title: 'API Keys', path: '/docs/boss/gateway/api-keys' },
          { title: 'Gateway Config', path: '/docs/boss/gateway/config' },
          { title: 'Moderation', path: '/docs/boss/gateway/moderation' },
          { title: 'Operations', path: '/docs/boss/gateway/operations' },
          { title: 'Audit Logs', path: '/docs/boss/gateway/audit' },
          { title: 'Service Registration', path: '/docs/boss/gateway/service-reg' },
        ],
      },
      {
        title: 'System Settings',
        path: '/docs/boss/settings',
        icon: 'ic-params',
        product: 'boss',
        children: [
          { title: 'Platform Settings', path: '/docs/boss/settings/platform' },
          { title: 'Rune Settings', path: '/docs/boss/settings/rune' },
          { title: 'Moha Settings', path: '/docs/boss/settings/moha' },
          { title: 'ChatApp Settings', path: '/docs/boss/settings/chatapp' },
          { title: 'Dynamic Dashboard', path: '/docs/boss/settings/dynamic-dashboard' },
          { title: 'Member Management', path: '/docs/boss/settings/members' },
          { title: 'License Management', path: '/docs/boss/settings/license' },
        ],
      },
      {
        title: 'Rune Admin',
        path: '/docs/boss/rune-admin',
        icon: 'ic-tour',
        product: 'boss',
        children: [
          { title: 'Clusters', path: '/docs/boss/rune-admin/clusters' },
          { title: 'Cluster Overview', path: '/docs/boss/rune-admin/cluster-overview' },
          { title: 'Kubernetes Resources', path: '/docs/boss/rune-admin/resources' },
          { title: 'Nodes & GPU Dashboard', path: '/docs/boss/rune-admin/nodes-gpu' },
          { title: 'Storage & Runtime Services', path: '/docs/boss/rune-admin/storage-runtime' },
          { title: 'Observability, Logs & Scheduling', path: '/docs/boss/rune-admin/observability' },
          { title: 'Resource Pools', path: '/docs/boss/rune-admin/resource-pools' },
          { title: 'Tenants & Quotas', path: '/docs/boss/rune-admin/tenants' },
          { title: 'Flavor Management', path: '/docs/boss/rune-admin/flavors' },
          { title: 'Private Images', path: '/docs/boss/rune-admin/templates' },
          { title: 'System Image Market', path: '/docs/boss/rune-admin/system-market' },
          { title: 'Built-in System Images', path: '/docs/boss/rune-admin/systems' },
        ],
      },
      {
        title: 'Moha Management',
        path: '/docs/boss/moha-admin',
        icon: 'ic-course',
        product: 'boss',
        children: [
          { title: 'Models', path: '/docs/boss/moha-console/model' },
          { title: 'Model Review', path: '/docs/boss/moha-admin/models' },
          { title: 'Datasets', path: '/docs/boss/moha-console/dataset' },
          { title: 'Dataset Review', path: '/docs/boss/moha-admin/datasets' },
          { title: 'Image Registry', path: '/docs/boss/moha-console/image' },
          { title: 'Image Review', path: '/docs/boss/moha-admin/images' },
          { title: 'Spaces', path: '/docs/boss/moha-console/space' },
          { title: 'Space Operations', path: '/docs/boss/moha-admin/spaces' },
          { title: 'Mirror Sources', path: '/docs/boss/moha-admin/mirrors' },
          { title: 'Organizations', path: '/docs/boss/moha-console/organization' },
          { title: 'Access Tokens', path: '/docs/boss/moha-console/token' },
        ],
      },
    ],
  },
];
