apiVersion: v1
kind: Service
metadata:
  name: {{ include "docs.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "docs.labels" . | nindent 4 }}
    {{- include "docs.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
  selector:
    {{- include "docs.selectorLabels" . | nindent 4 }}
