import type { DocsSidebarSection } from '../../toc';

export const MOHA_SIDEBAR_SECTIONS: DocsSidebarSection[] = [
  {
    subheader: 'Moha Repository',
    items: [
      {
        title: 'Home',
        path: '/moha',
        icon: 'ic-dashboard',
        deepMatch: false,
        product: 'moha',
      },
      {
        title: 'Quick Start',
        path: '/moha/quickstart',
        icon: 'ic-analytics',
        product: 'moha',
        children: [
          { title: 'Quick Start', path: '/moha/quickstart/guide' },
          { title: 'Account Settings', path: '/moha/quickstart/account' },
          { title: 'Access Tokens', path: '/moha/quickstart/token' },
        ],
      },
      {
        title: 'Home & Personal Workspace',
        path: '/moha/home',
        icon: 'ic-tour',
        product: 'moha',
        children: [
          { title: 'Overview', path: '/moha/home/overview' },
          { title: 'Created by Me', path: '/moha/home/created-by-me' },
          { title: 'Organizations', path: '/moha/home/organizations' },
          { title: 'Tokens & Announcements', path: '/moha/home/token-announcements' },
        ],
      },
      {
        title: 'Model Repositories',
        path: '/moha/models',
        icon: 'ic-course',
        product: 'moha',
        children: [
          { title: 'Model Hub Overview', path: '/moha/models/intro' },
          { title: 'Download Models', path: '/moha/models/download' },
          { title: 'Upload Models', path: '/moha/models/upload' },
          { title: 'Model Cards', path: '/moha/models/card' },
          { title: 'Model Versions', path: '/moha/models/version' },
        ],
      },
      {
        title: 'Datasets',
        path: '/moha/datasets',
        icon: 'ic-folder',
        product: 'moha',
        children: [
          { title: 'Dataset Overview', path: '/moha/datasets/info' },
          { title: 'Create Datasets', path: '/moha/datasets/create' },
          { title: 'Upload Datasets', path: '/moha/datasets/upload' },
          { title: 'Download Datasets', path: '/moha/datasets/download' },
          { title: 'Dataset Cards', path: '/moha/datasets/card' },
          { title: 'Dataset Maintenance', path: '/moha/datasets/maintain' },
          { title: 'Dataset File Rules', path: '/moha/datasets/rules' },
        ],
      },
      {
        title: 'Image Registry',
        path: '/moha/images',
        icon: 'ic-product',
        product: 'moha',
        children: [
          { title: 'Image Registry', path: '/moha/images' },
          { title: 'Image List & Filters', path: '/moha/images/gallery' },
        ],
      },
      {
        title: 'Spaces',
        path: '/moha/spaces',
        icon: 'ic-subpaths',
        product: 'moha',
        children: [
          { title: 'Spaces Overview', path: '/moha/spaces' },
          { title: 'Space List & Filters', path: '/moha/spaces/list' },
        ],
      },
      {
        title: 'Collaboration',
        path: '/moha/repository',
        icon: 'ic-file',
        product: 'moha',
        children: [
          { title: 'Repository Detail Layout', path: '/moha/repository/detail' },
          { title: 'Files & Version Browsing', path: '/moha/repository/files' },
          { title: 'Discussions & Collaboration', path: '/moha/repository/discussion' },
          { title: 'Repository Settings & Publishing', path: '/moha/repository/settings' },
        ],
      },
      {
        title: 'Advanced Integration',
        path: '/moha/advanced',
        icon: 'ic-tour',
        product: 'moha',
        children: [
          { title: 'API Integration', path: '/moha/advanced/api' },
          { title: 'CI/CD Workflows', path: '/moha/advanced/cicd' },
          { title: 'Performance Optimization', path: '/moha/advanced/optimization' },
          { title: 'Community Contribution', path: '/moha/advanced/contribution' },
        ],
      },
      {
        title: 'SDK Tutorial',
        path: '/moha/sdk-tutorial',
        icon: 'ic-job',
        product: 'moha',
        children: [
          { title: 'Quick Start', path: '/moha/sdk-tutorial/quick-start' },
          { title: 'SDK Overview', path: '/moha/sdk-tutorial/intro' },
          { title: 'Installation & Environment', path: '/moha/sdk-tutorial/install' },
          { title: 'Authentication & Tokens', path: '/moha/sdk-tutorial/authentication' },
          { title: 'CLI Reference', path: '/moha/sdk-tutorial/cli-reference' },
          { title: 'HubClient API', path: '/moha/sdk-tutorial/hub-api' },
          { title: 'Transfer & Sync', path: '/moha/sdk-tutorial/transfer' },
          { title: 'Data Encryption', path: '/moha/sdk-tutorial/encryption' },
          { title: 'Model Loading & Inference', path: '/moha/sdk-tutorial/transformers-datasets' },
          { title: 'Training & Export', path: '/moha/sdk-tutorial/training-export' },
          { title: 'Error Handling & FAQ', path: '/moha/sdk-tutorial/error-handling' },
        ],
      },
    ],
  },
];
